run:
  timeout: 5m

linters-settings:
  goimports:
    local-prefixes: github.com/luxfi/mpc

linters:
  disable-all: true
  enable:
    - goimports
    - govet
    - ineffassign
    - misspell
    - unconvert

issues:
  exclude-dirs:
    - vendor
    - .git
  max-issues-per-linter: 0
  max-same-issues: 0
