run:
  timeout: 5m

linters-settings:
  goimports:
    local-prefixes: github.com/luxfi/mpc

linters:
  enable:
    - goimports
    - govet
    - ineffassign
    - misspell
    - unconvert
    - typecheck
  disable:
    - errcheck
    - gosimple
    - staticcheck
    - unused

issues:
  exclude-dirs:
    - vendor
    - .git
  exclude-files:
    - ".*_test.go"
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0