run:
  timeout: 5m
  skip-dirs:
    - vendor
    - .git
  skip-files:
    - ".*_test.go"

linters-settings:
  goimports:
    local-prefixes: github.com/luxfi/mpc
  govet:
    check-shadowing: false

linters:
  enable:
    - goimports
    - govet
    - ineffassign
    - misspell
    - unconvert
    - typecheck
  disable:
    - errcheck
    - gosimple
    - staticcheck
    - unused

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0