apiVersion: hanzo.ai/v1alpha1
kind: IngressRoute
metadata:
  name: lux-mpc
  namespace: lux-mpc
  labels:
    app: lux-mpc
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`mpc.lux.network`) && PathPrefix(`/v1`)
      priority: 20
      services:
        - name: mpc-api-svc
          port: 8081
    - kind: Rule
      match: Host(`mpc.lux.network`) && Path(`/healthz`)
      priority: 20
      services:
        - name: mpc-api-svc
          port: 8081
    - kind: Rule
      match: Host(`mpc.lux.network`)
      priority: 1
      services:
        - name: mpc-dashboard-svc
          port: 3000
    - kind: Rule
      match: Host(`mpc-api.lux.network`)
      services:
        - name: mpc-api-svc
          port: 8081
  tls:
    certResolver: letsencrypt
    domains:
      - main: mpc.lux.network
      - main: mpc-api.lux.network
