#!/bin/bash

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                    🚀 Lux MPC Quick Start                     ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "Available commands:"
echo ""
echo "🏗️  Build & Setup:"
echo "   make build           - Build all binaries"
echo "   make clean           - Clean build artifacts"
echo ""
echo "🚀 Run MPC:"
echo "   make start           - Quick start (build + run services)"
echo "   make run-local       - Start NATS & Consul services"
echo "   make run-node0       - Start MPC node0"
echo "   make stop-local      - Stop all services"
echo "   make logs            - View service logs"
echo ""
echo "🧪 Testing:"
echo "   make test            - Run unit tests"
echo "   make e2e-test        - Run E2E tests"
echo "   make test-all        - Run all tests"
echo ""
echo "🛠️  MPC CLI Tools:"
echo "   ./lux-mpc-cli generate-peers -n 3       - Generate peers config"
echo "   ./lux-mpc-cli generate-identity         - Generate node identity"
echo "   ./lux-mpc-cli register-peers            - Register peers in Consul"
echo ""
echo "📝 Configuration:"
echo "   - Edit config.yaml.template for node configuration"
echo "   - Generated keys stored in ~/.lux-mpc/"
echo ""
echo "🎯 Quick start sequence:"
echo "   1. make start        (builds and starts services)"
echo "   2. make run-node0    (in new terminal)"
echo ""
echo "📌 Node Naming:"
echo "   Nodes are prefixed with environment: lux-{env}-{name}"
echo "   - Local: lux-local-node0"
echo "   - Testnet: lux-testnet-node0"
echo "   - Mainnet: lux-mainnet-node0"
echo ""
echo "Ready to start? Run: make start"